menu:
  杂文: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about
  宝藏: /tool

# gitalk
gitalk: true
gitalk_owner: weirui88888
gitalk_admin: [weirui88888]
gitalk_repo: gittalk
gitalk_client_id: Iv1.559cd3913fc25ee6
gitalk_client_secret: b9a2709d39ff416c5b7d8bd39b6b1672fca2c5cb
