menu:
  杂文: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about
  工具: /tool

# gitalk
gitalk: true
gitalk_owner: weirui88888
gitalk_admin: [weirui88888]
gitalk_repo: hexo
gitalk_client_id: 095d02e02b4cb9d84080
gitalk_client_secret: dea84a20fe0e77c570e0370c66eb7a0e9e2f29cb
