menu:
  杂文: /
  归档: /archives
  分类: /categories
  标签: /tags
  关于: /about
  工具: /tool

# gitalk
gitalk: true
gitalk_owner: weirui88888
gitalk_admin: [weirui88888]
gitalk_repo: gittalk
gitalk_client_id: Iv1.793919b109974338
gitalk_client_secret: bfb609148d838b9a52db2ccec2bbb7be7f842780
