name: Deploy Hexo To Oss

on:
  push:
    branches:
      - master

jobs:
  deploy: #job1 通过outpus共享变量给其下游的作业使用
    name: Deploy Hexo
    runs-on: ubuntu-latest
    outputs:
      deploy_version: ${{ steps.buildVersion.outputs.version }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{secrets.GITHUB_TOKEN}}

      - name: Fetch Sources
        uses: actions/checkout@v3
      
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Parse Changelog
        id: changelog
        uses: coditory/changelog-parser@v1

      - name: Install Dependencies & Build
        run: |
          npm install
          npm run clean
          npm run build
      
      - name: Prepare Static
        run: |
          mkdir static
          cp -r public/* static
          cp 404.html static
          echo "-------------------- static content start --------------------"
          ls static
          echo "-------------------- static content end ----------------------"

      - name: Upload Files To OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
            accessKeyId: ${{ secrets.ALI_ACCESS_KEY_ID }}
            accessKeySecret: ${{ secrets.ALI_ACCESS_KEY_SECRET }}
            bucket: newarray-hexo
            # use your own endpoint
            endpoint: oss-cn-hangzhou.aliyuncs.com
            folder: static
      
      - name: Build Version
        id: deployVersion
        run: |
          echo "-------------------- deploy version --------------------"
          echo "deploy_version=$(date "+%y%m%d").$GITHUB_RUN_NUMBER"
          echo "-------------------- deploy version --------------------"
          echo "deploy_version=$(date "+%y%m%d").$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "::set-output name=version::$(date "+%y%m%d").$GITHUB_RUN_NUMBER"

      - name: Package Static
        run: |
          tar -czf hexo-static-${{ steps.deployVersion.outputs.version }}.tar.gz ./static

      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
            | tr '\r\n' ' ' \
            | jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' \
          curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/{}
        

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{steps.changelog.outputs.version}}
          name: Release v${{steps.changelog.outputs.version}}
          body: ${{steps.changelog.outputs.description}}
          draft: true
          prerelease: false
          files: hexo-static-*.tar.gz

  View: # job2 这个可以叫做作业，作业中的steps叫做步骤，下面演示如何使用环境变量，以及使用上游作业中的变量
    name: View Env
    runs-on: ubuntu-latest
    steps:
      - name: View Env Detail
      # 环境变量可以不需要双引号包裹
        run: |
          echo $GITHUB_ACTION   
          echo $GITHUB_ACTOR
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_REF
          echo ${{needs.deploy.outputs.deploy_version}} 
        
      


          
          
