name: Deploy Hexo To Oss

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Hexo
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{secrets.HEXO_GITHUB_TOKEN}}

      - name: Fetch Sources
        uses: actions/checkout@v3
      
      - name: Setup Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Preview Rop
        run: |
          ls
